# Generated by Django 5.2.6 on 2025-10-06 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='course.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
            options={
                'indexes': [models.Index(fields=['enrollment', 'lesson'], name='progress_le_enrollm_32de2f_idx')],
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
    ]
