# Generated by Django 5.2.6 on 2025-10-04 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login_at', models.DateTimeField(auto_now=True)),
                ('total_courses_created', models.PositiveIntegerField(default=0)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login_at', models.DateTimeField(auto_now=True)),
                ('total_courses', models.PositiveIntegerField(default=0)),
                ('total_progress_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='ค่าเฉลี่ย % ความคืบหน้าของทุกคอร์ส', max_digits=5)),
                ('total_quizzes_passed', models.PositiveIntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
